### ISSUE TITLE
Not clear how to install "example" for version 1.3 

### ISSUE THREAD

**Issue by TaranuDev** [JGCRI/tethys#38]
Dear developer,

After installation of version 1.3 the examples are not provided, nor a reference .ini file.
It seems that the example file should be uploaded from zenodo, but it is not clear how.
Should we use the "example" from the v1.2? Some guiding will be much appreciated.

Cheers,
Sabin

**Comment by zarrarkhan** [comment]
Hi Sabin,

You can download the example data from: https://zenodo.org/record/4780604#.YXGH8Z7MJPY.

You can find relevant instructions for this on:
- The repo home page here: https://github.com/JGCRI/tethys#example-data
- As well as on the userguide here: https://jgcri.github.io/tethys/getting_started.html#installing-package-data

Let us know if you are able to run the example successfully.

Best
Zarrar

**Comment by TaranuDev** [comment]
Thanks a lot Zarrar!
