### ISSUE TITLE
随机森林降尺度问题

### ISSUE THREAD

**Issue by bzanniupie** [JGCRI/tethys#56]
最近在用随机森林算法对地下水降尺度，应用结果在空间表现上不太好，作出的图显示有条带化的现象，请问有人知道是什么原因吗？

**Comment by crvernon** [comment]
@ifthompson from Google Translate:

> Random Forest Downscaling Problem
> Recently, the random forest algorithm is used to downscale the groundwater. The result of the application is not very good in terms of spatial performance. The resulting map shows banding. Does anyone know the reason?

**Comment by ifthompson** [comment]
@bzanniupie 对不起，这个软件的目的是需水量降尺度，不是地下水，不使用随机森林算法，所以我不知道怎么帮忙。我的中文不太好，如果我误解了你的问题，请告诉我。
